exports.DAMI_DATA = {
    brand: "DAMILOLA",
    title: "Hi, I’m Osinaike Damilola",
    introduction: [
        "> self.profile();",
        '["Frontend Engineer focused on building fast, accessible, and scalable web applications."]',
        "",
        "> self.location();",
        '["London, UK (Remote / European time zones)"]',
        "",
        "> self.experience();",
        '["4+ years building production frontend applications for consumer-facing platforms"]',
        "",
        "> self.education();",
        '["MSc Engineering Management, De Montfort University", "B.Tech Civil Engineering"]',
        "",
        "> self.coreSkills();",
        '["TypeScript", "React", "Next.js", "Redux Toolkit", "TanStack Query", "HTML", "CSS", "Accessibility", "Performance Optimisation"]',
        "",
        "> self.tooling();",
        '["Playwright", "Jest", "GitHub Actions", "CI/CD", "Vercel", "Firebase", "Node.js"]',
        "",
        "> self.focusAreas();",
        '["User experience", "Frontend architecture", "Reusable component systems", "Cross-functional collaboration"]',
        "",
        "> self.contact();",
        '["GitHub", "Email"]',
    ],
    links: [{
        to: "mailto:osinaike.damilola@outlook.com",
        label: "Email",
    },
    {
        to: "https://github.com/ollah16",
        label: "GitHub",
    }]
}

exports.OLA_DATA = {
    brand: "OLAOLUWA",
    title: "Hi, I’m Olaoluwa Oke",
    introduction: [
        "> self.profile();",
        '["Frontend Engineer focused on building fast, accessible, and scalable web applications."]',
        "",
        "> self.location();",
        '["London, UK (Remote / European time zones)"]',
        "",
        "> self.experience();",
        '["4+ years building production frontend applications for consumer-facing platforms"]',
        "",
        "> self.education();",
        '["MSc Engineering Management, De Montfort University", "B.Tech Agricultural Engineering"]',
        "",
        "> self.coreSkills();",
        '["TypeScript", "React", "Next.js", "Redux Toolkit", "TanStack Query", "HTML", "CSS", "Accessibility", "Performance Optimisation"]',
        "",
        "> self.tooling();",
        '["Playwright", "Jest", "GitHub Actions", "CI/CD", "Vercel", "Firebase", "Node.js"]',
        "",
        "> self.focusAreas();",
        '["User experience", "Frontend architecture", "Reusable component systems", "Cross-functional collaboration"]',
        "",
        "> self.contact();",
        '["GitHub", "Email"]',
    ],
    links: [{
        to: "mailto:olaoluwa_oke@outlook.com",
        label: "Email",
    },
    {
        to: "https://github.com/ollah16",
        label: "GitHub",
    }]
}